package biblioteca;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileOutputStream;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

public class menu_2 extends javax.swing.JFrame {

    public ControladorFuncionario ctlFuncionarios;
    Funcionarios f;
    public ControladorCliente ctlCliente;
    Cliente c;
    public ControladorLivro ctlLivro;
    Livro l;

    /**
     * Creates new form menu_2
     */
    public menu_2() {
        ctlFuncionarios = new ControladorFuncionario();
        ctlCliente = new ControladorCliente();
        ctlLivro = new ControladorLivro();
        initComponents();
        JToggleButton bttListar1 = this.bttListar;
        bttListar1.doClick();
         JToggleButton bttListar2 = this.bttListar1;
        bttListar2.doClick();
         JToggleButton bttListar3 = this.bttListar2;
        bttListar3.doClick();
    }

     public void limpar(DefaultTableModel dtm) {
       dtm = (DefaultTableModel) TabelaFuncionario.getModel();

         int rowCount = dtm.getRowCount();
        
            for (int i = rowCount -1; i >= 0; i--) {
                dtm.removeRow(i);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        TelaPrincipal = new javax.swing.JPanel();
        TelaFuncionarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        bttAdicionar = new javax.swing.JToggleButton();
        bttSalvar = new javax.swing.JToggleButton();
        bttExcluir = new javax.swing.JToggleButton();
        txtIdade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bttBuscar = new javax.swing.JToggleButton();
        bttListar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFuncionario = new javax.swing.JTable();
        TelaClientes = new javax.swing.JPanel();
        bttAdicionar2 = new javax.swing.JToggleButton();
        bttListar2 = new javax.swing.JToggleButton();
        bttBuscar2 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        bttExcluir2 = new javax.swing.JToggleButton();
        txtNome2 = new javax.swing.JTextField();
        bttSalvar2 = new javax.swing.JToggleButton();
        txtCPF2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtID2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaFuncionario2 = new javax.swing.JTable();
        TelaLivros = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaFuncionario1 = new javax.swing.JTable();
        txtCPF1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSalario1 = new javax.swing.JTextField();
        bttAdicionar1 = new javax.swing.JToggleButton();
        bttSalvar1 = new javax.swing.JToggleButton();
        bttExcluir1 = new javax.swing.JToggleButton();
        txtIdade1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bttBuscar1 = new javax.swing.JToggleButton();
        bttListar1 = new javax.swing.JToggleButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaPrincipal.setLayout(new java.awt.CardLayout());

        jLabel1.setText("ID");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(142, 154, 166));

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Salario");

        bttAdicionar.setText("Adicionar");
        bttAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAdicionarActionPerformed(evt);
            }
        });

        bttSalvar.setText("Salvar");
        bttSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalvarActionPerformed(evt);
            }
        });

        bttExcluir.setText("Excluir");
        bttExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Idade");

        bttBuscar.setText("Buscar");
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });

        bttListar.setText("Listar");
        bttListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListarActionPerformed(evt);
            }
        });

        TabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Salario", "Idade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaFuncionario);

        javax.swing.GroupLayout TelaFuncionariosLayout = new javax.swing.GroupLayout(TelaFuncionarios);
        TelaFuncionarios.setLayout(TelaFuncionariosLayout);
        TelaFuncionariosLayout.setHorizontalGroup(
            TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaFuncionariosLayout.createSequentialGroup()
                        .addGroup(TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(TelaFuncionariosLayout.createSequentialGroup()
                                .addComponent(bttAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(bttBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(bttListar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TelaFuncionariosLayout.createSequentialGroup()
                                .addGroup(TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100))
                            .addGroup(TelaFuncionariosLayout.createSequentialGroup()
                                .addComponent(bttSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bttExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaFuncionariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        TelaFuncionariosLayout.setVerticalGroup(
            TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaFuncionariosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TelaFuncionariosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaFuncionariosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(TelaFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAdicionar)
                    .addComponent(bttSalvar)
                    .addComponent(bttExcluir)
                    .addComponent(bttBuscar)
                    .addComponent(bttListar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TelaPrincipal.add(TelaFuncionarios, "telaFCard");

        bttAdicionar2.setText("Adicionar");
        bttAdicionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAdicionar2ActionPerformed(evt);
            }
        });

        bttListar2.setText("Listar");
        bttListar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListar2ActionPerformed(evt);
            }
        });

        bttBuscar2.setText("Buscar");
        bttBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscar2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Nome");

        bttExcluir2.setText("Excluir");
        bttExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExcluir2ActionPerformed(evt);
            }
        });

        bttSalvar2.setText("Salvar");
        bttSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalvar2ActionPerformed(evt);
            }
        });

        jLabel14.setText("ID");

        txtID2.setEditable(false);
        txtID2.setBackground(new java.awt.Color(146, 158, 170));

        jLabel15.setText("CPF");

        TabelaFuncionario2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaFuncionario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncionario2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaFuncionario2);

        javax.swing.GroupLayout TelaClientesLayout = new javax.swing.GroupLayout(TelaClientes);
        TelaClientes.setLayout(TelaClientesLayout);
        TelaClientesLayout.setHorizontalGroup(
            TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaClientesLayout.createSequentialGroup()
                        .addGroup(TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TelaClientesLayout.createSequentialGroup()
                                .addComponent(bttAdicionar2)
                                .addGap(43, 43, 43)
                                .addComponent(bttBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(bttListar2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TelaClientesLayout.createSequentialGroup()
                                .addGroup(TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addComponent(txtCPF2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100))
                            .addGroup(TelaClientesLayout.createSequentialGroup()
                                .addComponent(bttSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bttExcluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 33, Short.MAX_VALUE))))
                    .addGroup(TelaClientesLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        TelaClientesLayout.setVerticalGroup(
            TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaClientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TelaClientesLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaClientesLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCPF2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGap(94, 94, 94)
                .addGroup(TelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAdicionar2)
                    .addComponent(bttSalvar2)
                    .addComponent(bttExcluir2)
                    .addComponent(bttBuscar2)
                    .addComponent(bttListar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TelaPrincipal.add(TelaClientes, "telaCCard");

        jLabel6.setText("ID");

        txtID1.setEditable(false);
        txtID1.setBackground(new java.awt.Color(153, 170, 186));

        jLabel7.setText("Nome");

        TabelaFuncionario1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Autor", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaFuncionario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncionario1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaFuncionario1);

        jLabel8.setText("Autor");

        jLabel9.setText("Quantidade");

        bttAdicionar1.setText("Adicionar");
        bttAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAdicionar1ActionPerformed(evt);
            }
        });

        bttSalvar1.setText("Salvar");
        bttSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalvar1ActionPerformed(evt);
            }
        });

        bttExcluir1.setText("Excluir");
        bttExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExcluir1ActionPerformed(evt);
            }
        });

        txtIdade1.setName("preco"); // NOI18N

        jLabel10.setText("Preço");

        bttBuscar1.setText("Buscar");
        bttBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscar1ActionPerformed(evt);
            }
        });

        bttListar1.setText("Listar");
        bttListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaLivrosLayout = new javax.swing.GroupLayout(TelaLivros);
        TelaLivros.setLayout(TelaLivrosLayout);
        TelaLivrosLayout.setHorizontalGroup(
            TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaLivrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaLivrosLayout.createSequentialGroup()
                        .addGroup(TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addGroup(TelaLivrosLayout.createSequentialGroup()
                                .addComponent(bttAdicionar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(bttBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(bttListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TelaLivrosLayout.createSequentialGroup()
                                .addGroup(TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100))
                            .addGroup(TelaLivrosLayout.createSequentialGroup()
                                .addComponent(bttSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bttExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        TelaLivrosLayout.setVerticalGroup(
            TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaLivrosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TelaLivrosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaLivrosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(TelaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAdicionar1)
                    .addComponent(bttSalvar1)
                    .addComponent(bttExcluir1)
                    .addComponent(bttBuscar1)
                    .addComponent(bttListar1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        TelaPrincipal.add(TelaLivros, "telaLCard");

        jMenu1.setText("Funcionarios");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Clientes");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Livros");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        
/*
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {                                       

        CardLayout clF = (CardLayout) TelaPrincipal.getLayout();
        clF.show(TelaPrincipal, "telaFCard");


    }                                      
*/
    private void bttAdicionarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario.getModel();
        int i = 0;
        try {

            f = ctlFuncionarios.getNovoFuncionarios();
            txtID.setText("" + f.getId());
            i++;

            int idade = parseInt(txtIdade.getText());
            int cpf = parseInt(txtCPF.getText());
            double salario = parseDouble(txtSalario.getText());

            f.setNome(txtNome.getText());
            f.setIdade(idade);
            f.setCPF(cpf);
            f.setSalario(salario);
            ctlFuncionarios.inserirFuncionarios(f);

            Object[] dados = {txtID.getText(), txtNome.getText(), txtCPF.getText(), txtSalario.getText(), txtIdade.getText()};
            dtm.addRow(dados);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }                                            

    private void bttSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ctlFuncionarios.salvar();
    }                                         

    private void bttExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario.getModel();
        try{
            for (Funcionarios x : ctlFuncionarios.listarFuncionarios()) {
                if (txtNome.getText().equals(x.getNome())) {
                    ctlFuncionarios.excluir(x);
                    dtm.removeRow(TabelaFuncionario.getSelectedRow());
                }
           } 
        } catch(Exception e){
            System.err.println(e.getMessage());
        }
    }                                          

    private void bttListarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario.getModel();
        limpar(dtm);
        int i =0;
        for (Funcionarios x : ctlFuncionarios.listarFuncionarios()) {
 
           /* if ((txtNome.getText()) != null) {
                dtm.removeRow(i);
            }*/
            Object[] dados = {x.getId(), x.getNome(), x.getCPF(), x.getSalario(), x.getIdade()};
            dtm.addRow(dados);

        }


    }                                         

    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario.getModel();
        int i = 0;

        for (Funcionarios x : ctlFuncionarios.listarFuncionarios()) {

            if ((txtNome.getText()) != null) {
                dtm.removeRow(i);
            }
            if (txtNome.getText().equals(x.getNome())) {

                Object[] dados = {x.getId(), x.getNome(), x.getCPF(), x.getSalario(), x.getIdade()};
                dtm.addRow(dados);

            }
            i++;
        }

    }                                         

    private void bttAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario1.getModel();
        int i = 0;
        try {

            l = ctlLivro.getNovoLivro();
            txtID1.setText("" + l.getId());
            i++;

            int quantidade = parseInt(txtSalario1.getText());
            int preco = parseInt(txtIdade1.getText());
            double salario = parseDouble(txtSalario1.getText());

            l.setNome(txtNome1.getText());
            l.setPreco(preco);
            l.setQuantidade(quantidade);
            l.setAutor(txtCPF1.getText());
            ctlLivro.inserirLivro(l);

            Object[] dados = {txtID1.getText(), txtNome1.getText(), txtCPF1.getText(), txtSalario1.getText(), txtIdade1.getText()};
            dtm.addRow(dados);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }                                             

    private void bttSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ctlLivro.salvar();
    }                                          

    private void bttExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario1.getModel();
        try{
            for (Livro x : ctlLivro.listarLivros()) {
                if (txtNome1.getText().equals(x.getNome())) {
                    ctlLivro.excluir(x);
                    dtm.removeRow(TabelaFuncionario1.getSelectedRow());
                }
           } 
        } catch(Exception e){
            System.err.println(e.getMessage());
        }
    }                                           

    private void bttBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario1.getModel();
        int i = 0;
        limpar(dtm);
        for (Livro x : ctlLivro.listarLivros()) {
            if (txtNome1.getText().equals(x.getNome())) {

                Object[] dados = {x.getId(), x.getNome(), x.getAutor(), x.getQuantidade(), x.getPreco()};
                dtm.addRow(dados);

            }
            i++;
        }

    }                                          

    private void bttListar1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario1.getModel();

        int i =0;
        for (Livro x : ctlLivro.listarLivros()) {
            Object[] dados = {x.getId(), x.getNome(), x.getAutor(), x.getQuantidade(), x.getPreco()};
            dtm.addRow(dados);

        }
    }                                          

    private void bttAdicionar2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario2.getModel();
        int i = 0;
        try {

            c = ctlCliente.getNovoCliente();
            txtID2.setText("" + c.getId());
            i++;

            int cpf = parseInt(txtCPF2.getText());

            c.setNome(txtNome2.getText());
            c.setCPF(cpf);
            ctlCliente.inserirCliente(c);

            Object[] dados = {txtID2.getText(), txtNome2.getText(), txtCPF2.getText()};
            dtm.addRow(dados);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }                                             

    private void bttListar2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario2.getModel();
        limpar(dtm);
        int i =0;
        for (Cliente x : ctlCliente.listarClientes()) {
            Object[] dados = {x.getId(), x.getNome(), x.getCPF()};
            dtm.addRow(dados);

        }
    }                                          

    private void bttBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario2.getModel();
        int i = 0;

        for (Cliente x : ctlCliente.listarClientes()) {
            if (txtNome2.getText().equals(x.getNome())) {
                Object[] dados = {x.getId(), x.getNome(), x.getCPF()};
                dtm.addRow(dados);

            }
            i++;
        }

    }                                          

    private void bttExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        DefaultTableModel dtm = (DefaultTableModel) TabelaFuncionario2.getModel();
        try{
            for (Cliente x : ctlCliente.listarClientes()) {
                if (txtNome2.getText().equals(x.getNome())) {
                    ctlCliente.excluir(x);
                    dtm.removeRow(TabelaFuncionario2.getSelectedRow());
                }
           } 
        } catch(Exception e){
            System.err.println(e.getMessage());
        }
    }                                           

    private void bttSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ctlCliente.salvar();
    }                                          
/*
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
    }                                      
*/
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {                                    
        CardLayout clL = (CardLayout) TelaPrincipal.getLayout();
        clL.show(TelaPrincipal, "telaLCard");
    }                                   

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {                                    
        CardLayout clC = (CardLayout) TelaPrincipal.getLayout();
        clC.show(TelaPrincipal, "telaCCard");
    }                                   

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        CardLayout clF = (CardLayout) TelaPrincipal.getLayout();
        clF.show(TelaPrincipal, "telaFCard");
    }                                   

    private void TabelaFuncionario2MouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
        
         if(TabelaFuncionario2.getSelectedRow() != -1){ //Passa jTextField o valor selecionado
            DefaultTableModel dtbProdutos = (DefaultTableModel) TabelaFuncionario2.getModel();
            txtID2.setText(TabelaFuncionario2.getValueAt(TabelaFuncionario2.getSelectedRow(), 0).toString());
            txtNome2.setText(TabelaFuncionario2.getValueAt(TabelaFuncionario2.getSelectedRow(), 1).toString());
            txtCPF2.setText(TabelaFuncionario2.getValueAt(TabelaFuncionario2.getSelectedRow(), 2).toString());
        }
    }                                               

    private void TabelaFuncionario1MouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
         if(TabelaFuncionario1.getSelectedRow() != -1){ //Passa jTextField o valor selecionado
            DefaultTableModel dtbProdutos = (DefaultTableModel) TabelaFuncionario1.getModel();
            txtID1.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 0).toString());
            txtNome1.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 1).toString());
            txtSalario1.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 2).toString());
            txtIdade1.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 3).toString());
            
        }
        
    }                                               

    private void TabelaFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
         if(TabelaFuncionario1.getSelectedRow() != -1){ //Passa jTextField o valor selecionado
            DefaultTableModel dtbProdutos = (DefaultTableModel) TabelaFuncionario1.getModel();
            txtID.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 0).toString());
            txtNome.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 1).toString());
            txtSalario.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 2).toString());
            txtIdade.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 3).toString());
            txtCPF.setText(TabelaFuncionario1.getValueAt(TabelaFuncionario1.getSelectedRow(), 3).toString());
            
        }
        
        
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable TabelaFuncionario;
    private javax.swing.JTable TabelaFuncionario1;
    private javax.swing.JTable TabelaFuncionario2;
    private javax.swing.JPanel TelaClientes;
    private javax.swing.JPanel TelaFuncionarios;
    private javax.swing.JPanel TelaLivros;
    private javax.swing.JPanel TelaPrincipal;
    private javax.swing.JToggleButton bttAdicionar;
    private javax.swing.JToggleButton bttAdicionar1;
    private javax.swing.JToggleButton bttAdicionar2;
    private javax.swing.JToggleButton bttBuscar;
    private javax.swing.JToggleButton bttBuscar1;
    private javax.swing.JToggleButton bttBuscar2;
    private javax.swing.JToggleButton bttExcluir;
    private javax.swing.JToggleButton bttExcluir1;
    private javax.swing.JToggleButton bttExcluir2;
    private javax.swing.JToggleButton bttListar;
    private javax.swing.JToggleButton bttListar1;
    private javax.swing.JToggleButton bttListar2;
    private javax.swing.JToggleButton bttSalvar;
    private javax.swing.JToggleButton bttSalvar1;
    private javax.swing.JToggleButton bttSalvar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPF1;
    private javax.swing.JTextField txtCPF2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtIdade1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNome2;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSalario1;
    // End of variables declaration                   
}
